import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
import {PGlite} from "@electric-sql/pglite";
test("discovery migration protects proposals, quotas, source provenance, atomic publication, and retries",async()=>{
 const db=new PGlite();
 const owner="00000000-0000-4000-8000-000000000001",other="00000000-0000-4000-8000-000000000002";
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; create table public.lab_specimens(id bigint generated always as identity primary key,code text,label text,notes text);`);
  await db.exec(await readFile(new URL("../docs/w4-rating.sql",import.meta.url),"utf8"));
  const migration=await readFile(new URL("../docs/ecosystem-discovery.sql",import.meta.url),"utf8");
  assert.doesNotMatch(migration,/\b(?:create|alter|drop)\s+policy\b/i);
  await db.exec(migration);
  await db.exec(migration);
  await db.query("insert into auth.users values($1),($2)",[owner,other]);
  await db.exec("set role anon");
  await assert.rejects(db.query("select public.punnett_begin_discovery('prompt','gemini-test')"),{code:"42501"});
  await assert.rejects(db.query("select * from public.punnett_discoveries"),{code:"42501"});
  await db.exec("reset role; set role authenticated");
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
  const started=await db.query<{result:{id:string}}>("select public.punnett_begin_discovery('Real discovery prompt','gemini-test') result");
  const id=started.rows[0].result.id;
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
  await assert.rejects(db.query("select public.punnett_discovery_proposal($1)",[id]),{code:"42501"});
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
  const label="Peacock mantis shrimp (Odontodactylus scyllarus)",facts="Odontodactylus scyllarus is a mantis shrimp with raptorial claws and exceptional vision in the Indo-Pacific.";
  await assert.rejects(db.query("select public.punnett_prepare_discovery($1,$2,$3,4316608,'Animalia','javascript:alert(1)','123')",[id,label,facts]),{code:"22023"});
  await db.query("select public.punnett_prepare_discovery($1,$2,$3,4316608,'Animalia','https://en.wikipedia.org/wiki/Odontodactylus_scyllarus','123')",[id,label,facts]);
  await db.query("select public.punnett_claim_discovery($1)",[id]);
  await assert.rejects(db.query("select public.punnett_claim_discovery($1)",[id]),{code:"P0001"});
  const captions=[`${label} — Nature issued this shrimp a very questionable set of cutlery.`,`${label} — Exceptional vision. No apparent interest in diplomacy.`];
  const publish="select public.punnett_publish_discovery($1,'data:image/png;base64,aQ==','Actual culture prompt','gemini-test',$2::jsonb) result";
  await assert.rejects(db.query(publish,[id,JSON.stringify(["Website caption"])]),{code:"22023"});
  const result=await db.query<{result:{image_id:string}}>(publish,[id,JSON.stringify(captions)]);
  assert.ok(result.rows[0].result.image_id);
  assert.equal((await db.query<{result:unknown}>(publish,[id,JSON.stringify(captions)])).rows[0].result && (await db.query<{result:{image_id:string}}>(publish,[id,JSON.stringify(captions)])).rows[0].result.image_id,result.rows[0].result.image_id);
  await db.exec("reset role");
  assert.equal((await db.query<{n:number}>("select count(*)::int n from public.lab_specimens")).rows[0].n,1);
  assert.equal((await db.query<{n:number}>("select count(*)::int n from public.punnett_generations")).rows[0].n,1);
  assert.equal((await db.query<{prompt:string}>("select prompt from public.punnett_discoveries")).rows[0].prompt,"Real discovery prompt");
  assert.equal((await db.query<{prompt:string}>("select prompt from public.punnett_generations")).rows[0].prompt,"Actual culture prompt");
  await db.exec("set role authenticated");
  for(let i=0;i<2;i++) await db.query("select public.punnett_begin_discovery('prompt','gemini-test')");
  await assert.rejects(db.query("select public.punnett_begin_discovery('prompt','gemini-test')"),{code:"P0001"});
  await db.exec("set role anon");
  const sources=await db.query<{result:Array<{label:string}>}>("select public.punnett_species_sources() result");
  assert.equal(sources.rows[0].result[0].label,label);
 } finally {await db.close();}
});
